import { type ReactNode, useEffect, useMemo, useRef, useState } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import {
  ArrowLeft, BatteryMedium, Bell, CalendarDays, ChevronRight, CirclePlay, Clock3,
  CloudRain, ContactRound, FileText, Folder, GalleryHorizontalEnd, Heart, Image,
  Instagram as InstagramIcon, LockKeyhole, MapPin, Menu, MessageCircle, Mic2, Music2, NotebookPen,
  Pause, Pencil, Phone as PhoneIcon, Play, Plus, Search, Send, Settings, ShieldCheck, Signal,
  Smartphone, Sparkles, Star, Trash2, UserRound, Volume2, X, Zap,
  Compass, MessageSquareQuote, AudioLines
} from 'lucide-react';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import { Router as WouterRouter, Route, Switch, useLocation } from 'wouter';
import { characterProfile, seedPhone, type PhoneStore, type Post, type GalleryItem, type DiaryEntry } from '@/phone/config';
import { PhoneApp, BrowserApp, EchoApp, StudioApp, PlacesApp, ScreenTimeApp } from '@/phone/NewApps';
import { StoryAdmin } from '@/phone/StoryAdmin';
import { VoiceMemos } from '@/phone/VoiceMemos';
import { publishActivity, type ReviewProposal } from '@/phone/publishActivity';
import { createContact } from '@/phone/createContact';

const queryClient = new QueryClient();
type AppId = 'phone' | 'messages' | 'instagram' | 'echo' | 'gallery' | 'music' | 'studio' | 'diary' | 'notes' | 'quick' | 'voice' | 'calendar' | 'places' | 'browser' | 'contacts' | 'notifications' | 'files' | 'screentime' | 'secret';
type Detail = { kind: string; id: string } | null;

const cloneSeed = (): PhoneStore => JSON.parse(JSON.stringify(seedPhone)) as PhoneStore;
const usePhoneStore = () => {
  const [store, setStore] = useState<PhoneStore>(() => {
    try {
      const parsed = JSON.parse(localStorage.getItem('hyunjin-phone-store') ?? '');
      const seed = cloneSeed();
      const merged = { ...seed };
      for (const key in seed) {
        if (parsed[key] !== undefined) {
          (merged as any)[key] = parsed[key];
        }
      }
      return merged as PhoneStore;
    } catch { return cloneSeed(); }
  });
  const currentStore = useRef(store);
  currentStore.current = store;
  const publish = (items: ReviewProposal[]) => {
    // Use the same localStorage record as Edit Mode. Commit before updating the UI,
    // so storage failure cannot be mistaken for a successful approval.
    const next = publishActivity(currentStore.current, items);
    const serialized = JSON.stringify(next);
    localStorage.setItem('hyunjin-phone-store', serialized);
    if (localStorage.getItem('hyunjin-phone-store') !== serialized) {
      throw new Error('Phone storage did not confirm the saved activity.');
    }
    currentStore.current = next;
    setStore(next);
  };
  useEffect(() => {
    try {
      localStorage.setItem('hyunjin-phone-store', JSON.stringify(store));
    } catch {
      console.warn('Phone storage is full. Remove a large uploaded or generated image before adding more.');
    }
  }, [store]);
  return [store, setStore, publish] as const;
};

const appMeta: Record<AppId, { label: string; icon: any; color: string }> = {
  phone: { label: 'Phone', icon: PhoneIcon, color: '#95b79d' },
  messages: { label: 'Messages', icon: MessageCircle, color: '#7b9bb9' },
  instagram: { label: 'Instagram', icon: InstagramIcon, color: '#b78a9d' },
  echo: { label: 'Echo', icon: MessageSquareQuote, color: '#a293b6' },
  gallery: { label: 'Gallery', icon: GalleryHorizontalEnd, color: '#bd9c68' },
  music: { label: 'Music', icon: Music2, color: '#9e80a9' },
  studio: { label: 'Studio', icon: AudioLines, color: '#bba78d' },
  diary: { label: 'Diary', icon: NotebookPen, color: '#c8919b' },
  notes: { label: 'Notes', icon: FileText, color: '#c6a568' },
  quick: { label: 'Quick Notes', icon: Zap, color: '#e0ad5c' },
  voice: { label: 'Voice Memos', icon: Mic2, color: '#858faf' },
  calendar: { label: 'Calendar', icon: CalendarDays, color: '#8cae98' },
  places: { label: 'Places', icon: MapPin, color: '#c49582' },
  browser: { label: 'Browser', icon: Compass, color: '#7ba1b9' },
  contacts: { label: 'Contacts', icon: ContactRound, color: '#8da5bd' },
  notifications: { label: 'Notifications', icon: Bell, color: '#ad879f' },
  files: { label: 'Files', icon: Folder, color: '#bd9e6e' },
  screentime: { label: 'Screen Time', icon: Clock3, color: '#858faf' },
  secret: { label: 'Secret Space', icon: LockKeyhole, color: '#8b829d' },
};

function Avatar({ initials, color, size = 'md' }: { initials: string; color: string; size?: 'sm' | 'md' | 'lg' }) {
  return <span className={`inline-flex shrink-0 items-center justify-center rounded-full font-semibold tracking-tight text-[#251e2b] ${size === 'sm' ? 'h-8 w-8 text-[10px]' : size === 'lg' ? 'h-16 w-16 text-lg' : 'h-11 w-11 text-xs'}`} style={{ background: `linear-gradient(145deg, ${color}, #f2d7bb)` }} data-testid={`avatar-${initials}`}>{initials}</span>;
}

function AppIcon({ id, small = false }: { id: AppId; small?: boolean }) {
  const meta = appMeta[id]; const Icon = meta.icon;
  return <span className={`inline-flex items-center justify-center rounded-[24%] text-[#241b26] shadow-lg transition-transform duration-300 group-hover:scale-105 ${small ? 'h-8 w-8 rounded-[27%]' : 'h-[3.35rem] w-[3.35rem]'}`} style={{ background: `linear-gradient(145deg, ${meta.color}, #e8d4bd)` }}><Icon size={small ? 15 : 25} strokeWidth={1.7} /></span>;
}

function Home({ onOpen, onSettings }: { onOpen: (id: AppId) => void; onSettings: () => void }) {
  const now = new Date();
  const time = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false });
  const date = now.toLocaleDateString([], { weekday: 'long', month: 'long', day: 'numeric' });
  const apps = Object.keys(appMeta) as AppId[];
  return <div className="relative flex min-h-[100dvh] flex-col overflow-hidden bg-[#11101c] px-5 pb-7 text-[#f3eee7] sm:mx-auto sm:min-h-0 sm:h-[844px] sm:max-w-[402px] sm:rounded-[44px] sm:border sm:border-white/15 sm:shadow-[0_30px_100px_rgba(0,0,0,.5)] phone-rise">
    <div className="absolute inset-0 overflow-hidden bg-[radial-gradient(circle_at_22%_18%,rgba(194,113,136,.46),transparent_32%),radial-gradient(circle_at_80%_42%,rgba(82,106,142,.55),transparent_36%),linear-gradient(158deg,#29243a_0%,#171525_52%,#0e101b_100%)]">
      <div className="absolute -right-24 top-40 h-80 w-80 rounded-full border border-[#f0c8ac]/20 blur-[1px]" /><div className="absolute -left-24 bottom-8 h-72 w-72 rounded-full bg-[#9d6e8c]/15 blur-3xl" /><div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-[#0b0d16]/80 to-transparent" />
    </div>
    <div className="relative z-10 flex items-center justify-between pt-4 text-[12px] font-semibold tracking-wide"><span data-testid="text-status-time">{time}</span><span className="absolute left-1/2 top-4 h-7 w-28 -translate-x-1/2 rounded-full bg-black shadow-lg" /><span className="flex items-center gap-1.5"><Signal size={13} /><span className="h-2 w-3 rounded-sm border border-current" /><BatteryMedium size={15} /></span></div>
    <div className="relative z-10 mt-12"><p className="text-[10px] uppercase tracking-[.28em] text-[#e7c8cc]/75">Hyunjin’s phone · {characterProfile.city}</p><h1 className="mt-3 font-serif text-[4.9rem] leading-[.84] tracking-[-.07em] text-[#fbf1e6]" data-testid="text-home-clock">{time}</h1><p className="mt-4 text-sm text-[#efe1db]/75" data-testid="text-home-date">{date}</p></div>
    <div className="relative z-10 mt-8 grid grid-cols-2 gap-3">
      <button className="glass group rounded-3xl p-4 text-left transition-transform active:scale-[.97]" onClick={() => onOpen('music')} data-testid="button-now-playing"><div className="flex items-center justify-between"><Music2 size={15} className="text-[#f1c7a4]" /><span className="flex gap-0.5">{[1, 2, 3, 4].map(i => <i key={i} className="h-3 w-0.5 origin-bottom animate-[wave_1.2s_ease-in-out_infinite] rounded-full bg-[#e5a9b3]" style={{ animationDelay: `${i * .12}s` }} />)}</span></div><p className="mt-5 truncate text-sm font-medium">Pink + White</p><p className="mt-1 truncate text-[10px] text-white/55">Frank Ocean · memory 14</p></button>
      <button className="glass rounded-3xl p-4 text-left transition-transform active:scale-[.97]" onClick={() => onOpen('diary')} data-testid="button-mood-widget"><div className="flex items-center justify-between"><CloudRain size={15} className="text-[#b7c9d6]" /><span className="text-[10px] text-white/50">22°</span></div><p className="mt-5 text-sm font-medium">soft rain in Seoul</p><p className="mt-1 text-[10px] text-white/55">near Hannam · mood: quiet</p></button>
    </div>
    <div className="relative z-10 mt-7 flex-1"><div className="mb-3 flex items-center justify-between"><span className="text-[10px] uppercase tracking-[.24em] text-white/45">all apps</span><button className="rounded-full p-1.5 text-white/55 transition-colors hover:bg-white/10 hover:text-white" onClick={onSettings} data-testid="button-open-settings"><Settings size={16} /></button></div><div className="grid grid-cols-4 gap-x-3 gap-y-5">
      {apps.map(id => <button key={id} className="group flex flex-col items-center gap-1.5 text-[10px] text-white/70 transition-colors hover:text-white" onClick={() => onOpen(id)} data-testid={`button-open-${id}`}><AppIcon id={id} /><span className="max-w-[4.4rem] truncate">{appMeta[id].label}</span></button>)}
    </div></div>
    <div className="glass relative z-10 mt-7 flex items-center justify-around rounded-[25px] p-3"><button onClick={() => onOpen('messages')} className="group" data-testid="button-dock-messages"><AppIcon id="messages" small /></button><button onClick={() => onOpen('gallery')} className="group" data-testid="button-dock-gallery"><AppIcon id="gallery" small /></button><button onClick={() => onOpen('music')} className="group" data-testid="button-dock-music"><AppIcon id="music" small /></button><button onClick={() => onOpen('notes')} className="group" data-testid="button-dock-notes"><AppIcon id="notes" small /></button></div>
    <div className="relative z-10 mx-auto mt-5 h-1 w-28 rounded-full bg-white/65" />
  </div>;
}

function AppHeader({ id, onBack, onSettings, editMode, onEdit }: { id: AppId; onBack: () => void; onSettings: () => void; editMode: boolean; onEdit: () => void }) {
  return <header className="flex items-center justify-between border-b border-white/10 px-5 pb-4 pt-5"><button onClick={onBack} className="rounded-full p-2 -ml-2 text-white/70 hover:bg-white/10 hover:text-white" data-testid="button-app-back"><ArrowLeft size={19} /></button><div className="flex items-center gap-2"><AppIcon id={id} small /><h2 className="font-serif text-xl">{appMeta[id].label}</h2></div><div className="flex items-center gap-1"><button onClick={onEdit} className={`rounded-full p-2 text-white/60 hover:bg-white/10 hover:text-white ${editMode ? 'bg-[#d98ca7]/20 text-[#f3c4c7]' : ''}`} data-testid="button-toggle-edit"><Pencil size={16} /></button><button onClick={onSettings} className="rounded-full p-2 text-white/60 hover:bg-white/10 hover:text-white" data-testid="button-app-settings"><Menu size={18} /></button></div></header>;
}

function Shell({ children, id, onBack, onSettings, editMode, onEdit }: { children: ReactNode; id: AppId; onBack: () => void; onSettings: () => void; editMode: boolean; onEdit: () => void }) {
  return <div className="relative flex min-h-[100dvh] flex-col overflow-hidden bg-[#12111d] text-[#f2ece5] sm:mx-auto sm:min-h-0 sm:h-[844px] sm:max-w-[402px] sm:rounded-[44px] sm:border sm:border-white/15 sm:shadow-[0_30px_100px_rgba(0,0,0,.5)] app-in"><AppHeader id={id} onBack={onBack} onSettings={onSettings} editMode={editMode} onEdit={onEdit} /><main className="scroll-thin flex-1 overflow-y-auto px-5 pb-10 pt-5">{children}</main><div className="pointer-events-none absolute inset-x-0 bottom-0 h-16 bg-gradient-to-t from-[#12111d] to-transparent" /></div>;
}

function ApprovedExtras({ store, app, detail, setDetail }: { store: PhoneStore; app: AppId; detail: Detail; setDetail: (d: Detail) => void }) {
  if (app === 'instagram') {
    const story = detail?.kind === 'approved-story' ? store.instagramStories.find(s => s.id === detail.id) : undefined;
    return story ? <div className="mb-5 rounded-3xl border border-white/10 bg-white/5 p-5">
      <button onClick={() => setDetail(null)} className="mb-4 text-xs text-[#e7aabb]">← stories</button>
      <p className="text-sm font-medium">{story.user} · {story.time}</p>
      {story.dataUrl && <img src={story.dataUrl} alt="" className="mt-3 w-full rounded-2xl" />}
      <p className="mt-4 text-sm">{story.caption}</p>
    </div> : store.instagramStories.length ? <div className="mb-5">
      <SectionTitle>new stories</SectionTitle><div className="flex gap-3 overflow-x-auto pb-2">
        {store.instagramStories.map(s => <button key={s.id} onClick={() => setDetail({ kind: 'approved-story', id: s.id })} className="min-w-20 rounded-2xl border border-[#d98ca7]/40 bg-white/5 p-3 text-left text-xs"><span className="block truncate">{s.user}</span><span className="mt-1 block text-[10px] text-white/40">{s.time}</span></button>)}
      </div>
    </div> : null;
  }
  if (app === 'gallery' && detail?.kind === 'album') {
    const photos = store.gallery.filter(g => detail.id === 'Favorites' ? g.favorite : g.album === detail.id);
    return <div className="mb-6"><button onClick={() => setDetail(null)} className="text-xs text-[#e7aabb]">← gallery</button><h3 className="mt-3 font-serif text-2xl">{detail.id}</h3><div className="mt-3 grid grid-cols-3 gap-2">{photos.map(g => <button key={g.id} onClick={() => setDetail({ kind: 'gallery', id: g.id })}><GalleryVisual item={g} /></button>)}</div></div>;
  }
  if (app === 'music' && store.musicActivity.length) return <div className="mb-5">
    <SectionTitle>recent listening</SectionTitle>
    {store.musicActivity.map(a => <div key={a.id} className="mb-2 rounded-2xl border border-white/10 bg-white/5 p-3"><p className="text-sm">{a.title}</p><p className="mt-1 text-xs text-white/55">{a.content} · {a.time}</p></div>)}
  </div>;
  return null;
}

function SectionTitle({ children, action, onAction }: { children: ReactNode; action?: string; onAction?: () => void }) {
  return <div className="mb-3 flex items-center justify-between"><h3 className="text-[10px] uppercase tracking-[.23em] text-white/45">{children}</h3>{action && <button onClick={onAction} className="text-xs text-[#e7aabb] hover:text-white" data-testid={`button-${action.toLowerCase().replaceAll(' ', '-')}`}>{action}</button>}</div>;
}
function Empty({ icon: Icon, title, body }: { icon: typeof Search; title: string; body: string }) {
  return <div className="flex flex-col items-center rounded-3xl border border-dashed border-white/15 px-7 py-14 text-center"><Icon size={25} className="mb-4 text-white/30" /><p className="font-serif text-xl">{title}</p><p className="mt-2 max-w-[15rem] text-xs leading-5 text-white/45">{body}</p></div>;
}

function Messages({ store, setStore, detail, setDetail, editMode }: { store: PhoneStore; setStore: React.Dispatch<React.SetStateAction<PhoneStore>>; detail: Detail; setDetail: (d: Detail) => void; editMode: boolean }) {
  const chat = detail?.kind === 'chat' ? store.messages.find(m => m.id === detail.id) : undefined;
  if (chat) return <div><button onClick={() => setDetail(null)} className="mb-5 flex items-center gap-2 text-sm text-[#e5a9b3]" data-testid="button-chat-back"><ArrowLeft size={15} /> conversations</button><div className="mb-6 flex items-center gap-3"><Avatar initials={chat.initials} color={chat.color} /><div><h3 className="font-serif text-2xl">{chat.person}</h3><p className="text-[11px] text-white/45">Messages · {chat.person === 'Antonella' ? 'Buenos Aires' : 'Hyune Studio'}</p></div></div><div className="space-y-3">{chat.messages.map((m, i) => <div key={i} className={`flex ${m.from === 'me' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[79%] rounded-2xl px-4 py-3 text-sm leading-5 ${m.from === 'me' ? 'rounded-br-md bg-[#d98ca7] text-[#2a1d27]' : 'rounded-bl-md bg-white/10 text-white/85'}`}>{m.kind === 'voice' ? <span className="flex items-center gap-2"><CirclePlay size={16} /> voice message · 0:18</span> : m.kind === 'photo' ? <span className="flex items-center gap-2 text-white/60"><Image size={16} /> photo attachment</span> : m.text}<span className={`mt-1 block text-[9px] ${m.from === 'me' ? 'text-[#4f2938]/70' : 'text-white/35'}`}>{m.time}</span></div></div>)}</div><div className="mt-7 flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-3 text-xs text-white/35"><span className="flex-1">iMessage</span><Send size={15} /></div></div>;
  const messages = store.messages;
  return <div><div className="mb-6"><p className="text-xs text-white/45">Tuesday, 28 May</p><h1 className="mt-1 font-serif text-4xl">Good evening.</h1></div><div className="mb-5 flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-3 py-2.5 text-xs text-white/40"><Search size={15} /> Search conversations</div><SectionTitle action="new" onAction={() => setStore(s => ({ ...s, messages: [{ id: `new-${Date.now()}`, person: 'New conversation', initials: 'N', preview: 'start writing something', time: 'now', color: '#c59ab3', messages: [] }, ...s.messages] }))}>pinned & recent</SectionTitle><div className="space-y-1">{messages.map(m => <button className="flex w-full items-center gap-3 rounded-2xl p-3 text-left transition-colors hover:bg-white/7" key={m.id} onClick={() => setDetail({ kind: 'chat', id: m.id })} data-testid={`card-conversation-${m.id}`}><div className="relative"><Avatar initials={m.initials} color={m.color} /><span className={`absolute bottom-0 right-0 h-2.5 w-2.5 rounded-full border-2 border-[#12111d] ${m.id === 'antonella' ? 'bg-[#a6d6b1]' : 'bg-white/20'}`} /></div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><span className="font-medium">{m.person}{m.pinned && <Star size={11} fill="#e7b967" className="ml-1.5 inline text-[#e7b967]" />}</span><span className="text-[10px] text-white/35">{m.time}</span></div><p className="mt-1 truncate text-xs text-white/45">{m.preview}</p></div>{m.unread && <span className="flex h-5 min-w-5 items-center justify-center rounded-full bg-[#d98ca7] px-1 text-[10px] text-[#291c26]">{m.unread}</span>}{editMode && <button onClick={(e) => { e.stopPropagation(); setStore(s => ({ ...s, messages: s.messages.filter(x => x.id !== m.id) })); }} className="rounded-full p-1.5 text-[#dd8998]" data-testid={`button-delete-message-${m.id}`}><Trash2 size={14} /></button>}</button>)}</div></div>;
}

function Instagram({ store, setDetail, detail }: { store: PhoneStore; setDetail: (d: Detail) => void; detail: Detail }) {
  const post = detail?.kind === 'post' ? store.posts.find(p => p.id === detail.id) : undefined;
  if (post) return <div><button onClick={() => setDetail(null)} className="mb-5 flex items-center gap-2 text-sm text-[#e5a9b3]" data-testid="button-post-back"><ArrowLeft size={15} /> feed</button><PostCard post={post} large /></div>;
  return <div><div className="flex items-start gap-4"><Avatar initials="H" color="#d895a6" size="lg" /><div className="flex-1"><div className="flex items-center justify-between"><div><h3 className="font-medium">hyune.studio</h3><p className="mt-1 text-xs text-white/45">Hyunjin · Seoul</p></div><button className="rounded-lg border border-white/15 px-3 py-1.5 text-[11px] text-white/70" data-testid="button-instagram-edit-profile">edit profile</button></div><div className="mt-4 flex gap-5 text-center text-xs"><span><b className="block text-sm text-white">38</b><span className="text-white/45">posts</span></span><span><b className="block text-sm text-white">2.4k</b><span className="text-white/45">following</span></span><span><b className="block text-sm text-white">11.8m</b><span className="text-white/45">quiet eyes</span></span></div></div></div><div className="mt-7 flex gap-4 overflow-x-auto pb-2">{['Close Friends', 'saved', 'tagged', 'activity'].map((x, i) => <button key={x} onClick={() => setDetail({ kind: 'ig-tab', id: x })} className="shrink-0 text-center" data-testid={`button-instagram-${x.replace(' ', '-')}`}><span className={`mx-auto flex h-12 w-12 items-center justify-center rounded-full border ${i === 0 ? 'border-[#d98ca7] bg-[#d98ca7]/20' : 'border-white/15 bg-white/5'}`}>{i === 0 ? <Heart size={16} /> : i === 1 ? <Star size={16} /> : <UserRound size={16} />}</span><span className="mt-2 block text-[10px] text-white/55">{x}</span></button>)}</div><SectionTitle>stories · today</SectionTitle><div className="mb-7 flex gap-3 overflow-x-auto">{['you', 'mar', 'mira', 'antonella'].map((x, i) => <button key={x} onClick={() => setDetail({ kind: 'story', id: x })} className="shrink-0 text-center" data-testid={`button-story-${x}`}><span className={`mx-auto flex h-14 w-14 items-center justify-center rounded-full border-2 ${i === 0 ? 'border-white/20 bg-white/5' : 'border-[#d98ca7] p-0.5'}`}><span className="flex h-full w-full items-center justify-center rounded-full bg-gradient-to-br from-[#394763] via-[#9d6f88] to-[#e9bb92] text-xs text-[#291f2b]">{x === 'you' ? <Plus size={17} /> : x.slice(0, 1).toUpperCase()}</span></span><span className="mt-1.5 block text-[10px] text-white/55">{x}</span></button>)}</div><div className="space-y-7">{store.posts.map(p => <PostCard key={p.id} post={p} onClick={() => setDetail({ kind: 'post', id: p.id })} />)}</div></div>;
}
function PostCard({ post, onClick, large }: { post: Post; onClick?: () => void; large?: boolean }) {
  return <article className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.045]" data-testid={`card-post-${post.id}`}><div className="flex items-center gap-2 px-4 py-3"><Avatar initials={post.user === 'mar.rivera' ? 'MR' : 'H'} color={post.tone === 'rose' ? '#d895a6' : '#e4b878'} size="sm" /><div className="flex-1"><p className="text-xs">{post.user}</p><p className="text-[10px] text-white/40">{post.time} · Seoul</p></div><button className="rounded-full p-1 text-white/45" data-testid={`button-post-more-${post.id}`}><Menu size={15} /></button></div><button onClick={onClick} className={`relative block w-full overflow-hidden bg-gradient-to-br ${post.tone === 'blue' ? 'from-[#1d3548] via-[#7188a1] to-[#d7a78e]' : post.tone === 'rose' ? 'from-[#3b283d] via-[#ba8291] to-[#f2c6aa]' : 'from-[#3d3022] via-[#b99362] to-[#e9cda5]'} ${large ? 'h-80' : 'h-56'}`} data-testid={`button-open-post-${post.id}`}>{post.dataUrl ? <img src={post.dataUrl} className="h-full w-full object-cover" /> : <><span className="absolute -right-12 top-8 h-52 w-52 rounded-full border border-white/25" /><span className="absolute bottom-8 left-8 font-serif text-3xl italic text-white/80">{post.tone === 'blue' ? 'blue hour' : post.tone === 'rose' ? 'after rain' : 'studio / 04'}</span></>}</button><div className="px-4 py-3"><div className="flex items-center gap-4"><button className="text-white/70 hover:text-[#ecabb8]" data-testid={`button-like-post-${post.id}`}><Heart size={17} /></button><button className="text-white/70" data-testid={`button-share-post-${post.id}`}><Send size={16} /></button><button className="ml-auto text-white/70" data-testid={`button-save-post-${post.id}`}><Star size={17} fill={post.saved ? '#e7b967' : 'none'} /></button></div><p className="mt-2 text-[11px] text-white/55">{post.likes.toLocaleString()} quiet likes</p><p className="mt-2 text-xs leading-5 text-white/80"><b className="mr-1 text-white">{post.user}</b>{post.caption}</p></div></article>;
}

function Gallery({ store, setDetail, detail, setStore, editMode }: { store: PhoneStore; setDetail: (d: Detail) => void; detail: Detail; setStore: React.Dispatch<React.SetStateAction<PhoneStore>>; editMode: boolean }) {
  const item = detail?.kind === 'gallery' ? store.gallery.find(g => g.id === detail.id) : undefined;
  if (item) return <div><button onClick={() => setDetail(null)} className="mb-5 flex items-center gap-2 text-sm text-[#e5a9b3]" data-testid="button-gallery-back"><ArrowLeft size={15} /> gallery</button><GalleryVisual item={item} large /><div className="mt-5"><div className="flex items-center justify-between"><div><h3 className="font-serif text-2xl">{item.title}</h3><p className="mt-1 text-xs text-white/45">{item.date}</p></div><button className="rounded-full border border-white/15 p-3 text-[#e7b967]" data-testid="button-favorite-gallery"><Heart size={17} fill={item.favorite ? 'currentColor' : 'none'} /></button></div><p className="mt-5 text-sm leading-6 text-white/65">{item.caption}</p><p className="mt-5 text-[10px] uppercase tracking-[.2em] text-white/35">album · {item.album} · captured on this phone</p></div></div>;
  const albums = [...new Set(['Favorites', 'Screenshots', 'Videos', 'Sketches', 'Seoul', 'Buenos Aires', 'Friends', 'Antonella', 'Art & Design', 'Random Photos', ...store.gallery.map(g => g.album)])];
  return <div><div className="mb-7"><p className="text-xs text-white/45">6 albums · 128 items</p><h1 className="mt-1 font-serif text-4xl">Gallery</h1></div><div className="grid grid-cols-2 gap-2">{albums.map((a, i) => { const first = store.gallery.find(x => x.album === a) ?? store.gallery[i % store.gallery.length]; return <button key={a} onClick={() => setDetail({ kind: 'album', id: a })} className="group relative overflow-hidden rounded-2xl bg-white/5 p-3 text-left" data-testid={`card-album-${a.replaceAll(' ', '-').toLowerCase()}`}><GalleryVisual item={first} /><span className="absolute inset-x-3 bottom-3 rounded-xl bg-[#12111d]/70 px-3 py-2 backdrop-blur-sm"><b className="block text-xs">{a}</b><small className="text-[10px] text-white/50">{a === 'Favorites' ? '12' : i + 7} items</small></span></button>; })}</div><SectionTitle action={editMode ? 'add' : undefined} onAction={() => setStore(s => ({ ...s, gallery: [{ id: `g-${Date.now()}`, title: 'new photograph', album: 'Random Photos', date: 'Today', caption: 'a new memory waiting for a caption', tone: 'violet' }, ...s.gallery] }))}>recently captured</SectionTitle><div className="grid grid-cols-3 gap-2">{store.gallery.map(g => <button onClick={() => setDetail({ kind: 'gallery', id: g.id })} key={g.id} className="relative overflow-hidden rounded-xl" data-testid={`card-gallery-${g.id}`}><GalleryVisual item={g} /><span className="absolute left-2 top-2 rounded-full bg-black/30 p-1 text-white/70">{g.favorite && <Heart size={10} fill="currentColor" />}</span></button>)}</div></div>;
}
function GalleryVisual({ item, large }: { item: GalleryItem; large?: boolean }) { const tones: Record<string, string> = { rose: 'from-[#422a40] via-[#c28493] to-[#f0c6aa]', blue: 'from-[#182c43] via-[#66829d] to-[#d9a78d]', ink: 'from-[#141923] via-[#536173] to-[#c9b49f]', green: 'from-[#233d39] via-[#73977e] to-[#d4bc96]', violet: 'from-[#282246] via-[#71638e] to-[#d3a1a0]', amber: 'from-[#46331f] via-[#aa8152] to-[#e0bd87]' }; return <div className={`relative w-full overflow-hidden bg-gradient-to-br ${tones[item.tone] ?? tones.blue} ${large ? 'h-64 rounded-3xl' : 'aspect-square'}`}>{item.dataUrl ? <img src={item.dataUrl} className="h-full w-full object-cover opacity-80" /> : <><span className="absolute left-[18%] top-[20%] h-[44%] w-[45%] rounded-full border border-white/25" /><span className="absolute bottom-[14%] right-[13%] h-[38%] w-[30%] rounded-t-full border border-white/20" /></>}<span className="absolute bottom-3 left-3 text-[9px] tracking-wide text-white/60">{item.title}</span></div>; }

function Diary({ store, setStore, detail, setDetail, editMode }: { store: PhoneStore; setStore: React.Dispatch<React.SetStateAction<PhoneStore>>; detail: Detail; setDetail: (d: Detail) => void; editMode: boolean }) {
  const entry = detail?.kind === 'diary' ? store.diary.find(d => d.id === detail.id) : undefined;
  if (entry) return <div><button onClick={() => setDetail(null)} className="mb-5 flex items-center gap-2 text-sm text-[#e5a9b3]" data-testid="button-diary-back"><ArrowLeft size={15} /> all entries</button><p className="text-xs text-white/45">{entry.date} · {entry.mood}</p><h1 className="mt-3 font-serif text-4xl leading-tight">{entry.title || 'Untitled entry'}</h1><div className="mt-8 whitespace-pre-line text-[15px] leading-7 text-white/70">{entry.body}</div>{editMode && <button onClick={() => { setStore(s => ({ ...s, diary: s.diary.filter(x => x.id !== entry.id) })); setDetail(null); }} className="mt-10 flex items-center gap-2 rounded-xl border border-[#dd8998]/30 px-3 py-2 text-xs text-[#e3a3b1]" data-testid={`button-delete-diary-${entry.id}`}><Trash2 size={14} /> delete entry</button>}</div>;
  return <div><div className="mb-7 flex items-end justify-between"><div><p className="text-xs text-white/45">private, only on this phone</p><h1 className="mt-1 font-serif text-4xl">Diary</h1></div>{editMode && <button onClick={() => { const d: DiaryEntry = { id: `d-${Date.now()}`, date: 'Today', title: 'new page', mood: 'unfolding', body: 'Write what you noticed.' }; setStore(s => ({ ...s, diary: [d, ...s.diary] })); setDetail({ kind: 'diary', id: d.id }); }} className="rounded-full bg-[#d98ca7] p-3 text-[#2b1d27]" data-testid="button-add-diary"><Plus size={17} /></button>}</div><div className="mb-6 flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-3 py-2.5 text-xs text-white/40"><Search size={15} /> search pages</div><div className="space-y-3">{store.diary.map(d => <button key={d.id} onClick={() => setDetail({ kind: 'diary', id: d.id })} className="w-full rounded-3xl border border-white/10 bg-white/[.045] p-5 text-left transition-colors hover:bg-white/[.08]" data-testid={`card-diary-${d.id}`}><div className="flex justify-between text-[10px] uppercase tracking-[.17em] text-white/35"><span>{d.date}</span><span>{d.mood}</span></div><h3 className="mt-4 font-serif text-xl">{d.title || 'Untitled entry'}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-white/50">{d.body}</p><span className="mt-4 flex items-center gap-1 text-[10px] text-[#dfa4b2]">read page <ChevronRight size={13} /></span></button>)}</div></div>;
}

function QuickNotes({ store, setStore, editMode }: { store: PhoneStore; setStore: React.Dispatch<React.SetStateAction<PhoneStore>>; editMode: boolean }) {
  const add = () => setStore(s => ({ ...s, quickNotes: [{ id: `q-${Date.now()}`, text: 'a new thought, before it disappears', time: 'just now', color: '#d895a6' }, ...s.quickNotes] }));
  return <div><div className="mb-7 flex items-end justify-between"><div><p className="text-xs text-white/45">the loose pieces</p><h1 className="mt-1 font-serif text-4xl">Quick Notes</h1></div><button onClick={add} className="rounded-full bg-[#d98ca7] p-3 text-[#2b1d27]" data-testid="button-add-quick-note"><Plus size={17} /></button></div><div className="space-y-2">{store.quickNotes.map(n => <div key={n.id} className="group flex items-start gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4" data-testid={`card-quick-note-${n.id}`}><span className="mt-1 h-2 w-2 rounded-full" style={{ backgroundColor: n.color }} /><div className="min-w-0 flex-1"><p className="text-sm leading-5 text-white/80">{n.text}</p><p className="mt-2 text-[10px] text-white/35">{n.time}</p></div>{(editMode || n.id.startsWith('q-')) && <button onClick={() => setStore(s => ({ ...s, quickNotes: s.quickNotes.filter(x => x.id !== n.id) }))} className="rounded-full p-1 text-white/25 hover:text-[#df8999]" data-testid={`button-delete-quick-note-${n.id}`}><Trash2 size={14} /></button>}</div>)}</div></div>;
}

function Notes({ store, setDetail }: { store: PhoneStore; setDetail: (d: Detail) => void }) {
  return <div><div className="mb-7"><p className="text-xs text-white/45">organized thoughts</p><h1 className="mt-1 font-serif text-4xl">Notes</h1></div><div className="grid gap-3">{store.notes.map(n => <button key={n.id} onClick={() => setDetail({ kind: 'note', id: n.id })} className="flex items-start gap-4 rounded-3xl border border-white/10 bg-white/[.045] p-5 text-left hover:bg-white/[.08]" data-testid={`card-note-${n.id}`}><span className="mt-1 h-3 w-3 rounded-full" style={{ background: n.color }} /><div className="flex-1"><h3 className="font-serif text-lg">{n.title}</h3><p className="mt-1 text-[10px] text-white/35">{n.meta}</p><p className="mt-3 line-clamp-1 text-xs text-white/45">{n.body}</p></div><ChevronRight size={16} className="mt-1 text-white/25" /></button>)}</div></div>;
}

function Voice({ store, setDetail, detail, setStore, editMode }: { store: PhoneStore; setDetail: (d: Detail) => void; detail: Detail; setStore: React.Dispatch<React.SetStateAction<PhoneStore>>; editMode: boolean }) {
  return <VoiceMemos store={store} setStore={setStore} detail={detail} setDetail={setDetail} editMode={editMode} />;
}

function Calendar({ store, setStore, editMode }: { store: PhoneStore; setStore: React.Dispatch<React.SetStateAction<PhoneStore>>; editMode: boolean }) {
  const days = Array.from({ length: 30 }, (_, i) => i + 1); const add = () => setStore(s => ({ ...s, events: [...s.events, { id: `e-${Date.now()}`, day: 28, title: 'new plan', time: '19:00', kind: 'personal' }] }));
  return <div><div className="mb-7 flex items-end justify-between"><div><p className="text-xs text-white/45">Seoul · June 2024</p><h1 className="mt-1 font-serif text-4xl">Calendar</h1></div>{editMode && <button onClick={add} className="rounded-full bg-[#d98ca7] p-3 text-[#2b1d27]" data-testid="button-add-event"><Plus size={17} /></button>}</div><div className="rounded-3xl border border-white/10 bg-white/[.045] p-4"><div className="mb-3 grid grid-cols-7 text-center text-[9px] uppercase tracking-widest text-white/35">{['S','M','T','W','T','F','S'].map((d, i) => <span key={`${d}${i}`}>{d}</span>)}</div><div className="grid grid-cols-7 gap-y-2 text-center text-xs">{days.map(d => <button key={d} className={`relative mx-auto flex h-8 w-8 items-center justify-center rounded-full ${d === 28 ? 'bg-[#d98ca7] text-[#2c1d27]' : 'text-white/65 hover:bg-white/10'}`} data-testid={`button-calendar-day-${d}`}>{d}{store.events.some(e => e.day === d) && <i className="absolute bottom-0.5 h-1 w-1 rounded-full bg-[#e7bb77]" />}</button>)}</div></div><SectionTitle>up next</SectionTitle><div className="space-y-2">{store.events.map(e => <div key={e.id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4" data-testid={`card-event-${e.id}`}><span className="w-8 text-center font-serif text-xl text-[#e4b6a8]">{e.day}</span><div className="h-8 w-px bg-white/15" /><div className="flex-1"><p className="text-sm">{e.title}</p><p className="mt-1 text-[10px] text-white/40">{e.time} · {e.kind}</p></div>{editMode && <button onClick={() => setStore(s => ({ ...s, events: s.events.filter(x => x.id !== e.id) }))} className="text-white/25 hover:text-[#dd8998]" data-testid={`button-delete-event-${e.id}`}><Trash2 size={14} /></button>}</div>)}</div></div>;
}

function Contacts({ store, setDetail, detail }: { store: PhoneStore; setDetail: (d: Detail) => void; detail: Detail }) {
  const c = detail?.kind === 'contact' ? store.contacts.find(x => x.id === detail.id) : undefined;
  if (c) return <div><button onClick={() => setDetail(null)} className="mb-5 flex items-center gap-2 text-sm text-[#e5a9b3]" data-testid="button-contact-back"><ArrowLeft size={15} /> contacts</button><div className="flex flex-col items-center text-center"><Avatar initials={c.initials} color={c.color} size="lg" /><h1 className="mt-4 font-serif text-3xl">{c.name}</h1><p className="mt-1 text-xs text-white/45">{c.role} · {c.context}</p><div className="mt-5 flex gap-3"><button className="flex items-center gap-2 rounded-xl bg-[#d98ca7] px-4 py-2 text-xs text-[#2b1d27]" data-testid="button-contact-message"><MessageCircle size={14} /> message</button><button className="flex items-center gap-2 rounded-xl border border-white/15 px-4 py-2 text-xs" data-testid="button-contact-call"><PhoneIcon size={14} /> call</button></div></div><div className="mt-10 rounded-3xl border border-white/10 bg-white/[.045] p-5"><p className="text-[10px] uppercase tracking-[.2em] text-white/35">context note</p><p className="mt-3 text-sm leading-6 text-white/65">{c.id.startsWith('contact-') ? c.context : c.name === 'Antonella' ? 'Remember the tiny cinema in Euljiro. She likes the seats in the back row.' : 'A good person to have nearby when a project gets complicated.'}</p></div></div>;
  return <div><div className="mb-7"><p className="text-xs text-white/45">people kept close</p><h1 className="mt-1 font-serif text-4xl">Contacts</h1></div><div className="mb-5 flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-3 py-2.5 text-xs text-white/40"><Search size={15} /> search people</div><div className="space-y-2">{store.contacts.map(cn => <button key={cn.id} onClick={() => setDetail({ kind: 'contact', id: cn.id })} className="flex w-full items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4 text-left hover:bg-white/[.08]" data-testid={`card-contact-${cn.id}`}><Avatar initials={cn.initials} color={cn.color} /><span className="flex-1"><b className="block text-sm">{cn.name}</b><small className="mt-1 block text-[10px] text-white/40">{cn.role} · {cn.context}</small></span><ChevronRight size={15} className="text-white/25" /></button>)}</div></div>;
}

function Music({ setDetail, detail }: { setDetail: (d: Detail) => void; detail: Detail }) {
  if (detail?.kind === 'playlist') return <div><button onClick={() => setDetail(null)} className="mb-5 flex items-center gap-2 text-sm text-[#e5a9b3]" data-testid="button-playlist-back"><ArrowLeft size={15} /> music</button><div className="flex items-end gap-4"><div className="flex h-28 w-28 items-center justify-center rounded-3xl bg-gradient-to-br from-[#e0a8a9] via-[#9a7b9d] to-[#28334c] shadow-lg"><Music2 size={35} className="text-white/80" /></div><div><p className="text-[10px] uppercase tracking-[.2em] text-white/40">playlist</p><h1 className="mt-1 font-serif text-3xl">{detail.id}</h1><p className="mt-1 text-xs text-white/45">12 songs · made slowly</p></div></div><div className="mt-8 space-y-1">{['Pink + White', 'The Louvre', 'Garden Song', 'Mystery of Love', 'Nights'].map((x, i) => <button key={x} className="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-white/10" data-testid={`button-song-${i}`}><span className="w-5 text-center text-xs text-white/30">{i + 1}</span><span className="flex-1 text-sm">{x}</span><span className="text-[10px] text-white/35">3:{12 + i * 8}</span><Play size={14} className="text-white/30" /></button>)}</div></div>;
  return <div><div className="mb-7"><p className="text-xs text-white/45">soundtrack, mostly after dark</p><h1 className="mt-1 font-serif text-4xl">Music</h1></div><div className="overflow-hidden rounded-3xl bg-gradient-to-br from-[#614a6b] via-[#a87888] to-[#e1b990] p-5"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-[.2em] text-white/65">now playing</span><Volume2 size={15} /></div><div className="mt-12"><p className="font-serif text-3xl">Pink + White</p><p className="mt-1 text-xs text-white/65">Frank Ocean · Blonde</p></div><div className="mt-5 h-1 rounded-full bg-white/25"><span className="block h-1 w-[43%] rounded-full bg-white/80" /></div><div className="mt-2 flex justify-between text-[9px] text-white/60"><span>1:48</span><span>3:04</span></div><div className="mt-5 flex justify-center"><button className="flex h-11 w-11 items-center justify-center rounded-full bg-white text-[#503b57]" data-testid="button-music-play"><Pause size={18} fill="currentColor" /></button></div></div><SectionTitle>playlists</SectionTitle><div className="grid grid-cols-2 gap-3">{['night walks', 'for Antonella', 'studio light', 'memory 14'].map((x, i) => <button key={x} onClick={() => setDetail({ kind: 'playlist', id: x })} className="rounded-2xl border border-white/10 bg-white/[.045] p-4 text-left" data-testid={`card-playlist-${i}`}><span className="flex h-14 w-full items-center justify-center rounded-xl bg-gradient-to-br from-[#39405b] to-[#bc8998]"><Music2 size={22} className="text-white/70" /></span><p className="mt-3 text-sm">{x}</p><p className="mt-1 text-[10px] text-white/40">{i + 7} songs</p></button>)}</div></div>;
}

function Notifications({ store }: { store: PhoneStore }) { const icons: Record<string, any> = { message: MessageCircle, instagram: InstagramIcon, calendar: CalendarDays, notebook: NotebookPen, music: Music2 }; return <div><div className="mb-7"><p className="text-xs text-white/45">while you were away</p><h1 className="mt-1 font-serif text-4xl">Activity</h1></div><div className="space-y-2">{store.notifications.map((n, i) => { const I = icons[n.icon] || Bell; return <button key={n.id} className="flex w-full items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4 text-left hover:bg-white/[.08]" data-testid={`card-notification-${i}`}><span className="flex h-10 w-10 items-center justify-center rounded-xl" style={{ background: `${n.color}35`, color: n.color }}><I size={17} /></span><span className="flex-1"><b className="block text-xs font-medium">{n.title}</b><small className="mt-1 block text-[10px] text-white/40">{n.sub}</small></span><ChevronRight size={15} className="text-white/20" /></button>; })}</div>{store.notifications.length === 0 && <Empty icon={Bell} title="That’s everything" body="New little things will appear here as the day moves on." />}</div>; }
function Files({ store }: { store: PhoneStore }) { const folders = [{ n: 'Artwork', t: 'rose' }, { n: 'Design References', t: 'blue' }, { n: 'Documents', t: 'amber' }, { n: 'Sketches', t: 'ink' }, { n: 'Music Ideas', t: 'violet' }, { n: 'RP Materials', t: 'green' }]; return <div><div className="mb-7"><p className="text-xs text-white/45">on this phone</p><h1 className="mt-1 font-serif text-4xl">Files</h1></div><div className="mb-5 flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-3 py-2.5 text-xs text-white/40"><Search size={15} /> search files</div><div className="grid grid-cols-2 gap-3">{folders.map((f, i) => { const c = store.files.filter(x => x.folder === f.n).length; return <button key={f.n} className="rounded-3xl border border-white/10 bg-white/[.045] p-4 text-left hover:bg-white/[.08]" data-testid={`card-folder-${i}`}><span className={`flex h-12 w-12 items-center justify-center rounded-2xl ${f.t === 'rose' ? 'bg-[#c68ba0]/35 text-[#e3a8b5]' : f.t === 'blue' ? 'bg-[#8aaac0]/30 text-[#a9c8d5]' : f.t === 'amber' ? 'bg-[#d3a760]/30 text-[#e4c17e]' : f.t === 'violet' ? 'bg-[#9d87b6]/30 text-[#c3afd7]' : f.t === 'green' ? 'bg-[#86ad92]/30 text-[#b6d1b4]' : 'bg-white/10 text-white/60'}`}><Folder size={22} /></span><p className="mt-4 text-sm">{f.n}</p><p className="mt-1 text-[10px] text-white/40">{c} files</p></button>; })}</div><div className="mt-7 rounded-3xl border border-white/10 bg-white/[.045] p-5"><p className="text-[10px] uppercase tracking-[.2em] text-white/35">recently opened</p>{store.files.slice(0,3).map((x, i) => <button key={x.id} className="mt-4 flex w-full items-center gap-3 text-left" data-testid={`button-file-${i}`}><FileText size={16} className="text-white/45" /><span className="flex-1 text-xs">{x.name}</span><span className="text-[10px] text-white/30">{x.date}</span></button>)}</div></div>; }

function Secret({ unlocked, setUnlocked }: { unlocked: boolean; setUnlocked: (v: boolean) => void }) { const [pin, setPin] = useState(''); const unlock = () => { if (pin === '1428' || pin === '0000') setUnlocked(true); else setPin(''); }; if (!unlocked) return <div className="flex min-h-[65vh] flex-col items-center justify-center text-center"><span className="flex h-20 w-20 items-center justify-center rounded-[28px] border border-[#d98ca7]/35 bg-[#d98ca7]/10 text-[#e8acb8]"><LockKeyhole size={31} /></span><h1 className="mt-6 font-serif text-3xl">Secret Space</h1><p className="mt-2 max-w-[15rem] text-xs leading-5 text-white/45">A discreet room for the things that do not need to be explained.</p><div className="mt-8 flex gap-2"><input value={pin} onChange={e => setPin(e.target.value.replace(/\\D/g, '').slice(0, 4))} onKeyDown={e => e.key === 'Enter' && unlock()} type="password" inputMode="numeric" placeholder="passcode" className="w-28 rounded-xl border border-white/15 bg-white/5 px-3 py-2 text-center text-sm tracking-[.4em] outline-none focus:border-[#d98ca7]" data-testid="input-secret-passcode" /><button onClick={unlock} className="rounded-xl bg-[#d98ca7] px-4 py-2 text-xs text-[#291d26]" data-testid="button-unlock-secret">unlock</button></div><p className="mt-4 text-[10px] text-white/25">try 1428</p></div>; const rooms = ['Private Diary', 'Inner Thoughts', 'Private Voice Memos', 'Memories', 'Things About Antonella', 'Unfinished Ideas', 'Locked Memories']; return <div><div className="mb-8 flex items-center justify-between"><div><p className="text-xs text-[#e2aab6]">unlocked · face id approved</p><h1 className="mt-1 font-serif text-4xl">Secret Space</h1></div><ShieldCheck className="text-[#d98ca7]" size={22} /></div><div className="space-y-2">{rooms.map((x, i) => <button key={x} className="flex w-full items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4 text-left hover:bg-white/[.08]" data-testid={`button-secret-room-${i}`}><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#d98ca7]/15 text-[#e3a7b4]">{i === 0 ? <NotebookPen size={16} /> : i === 2 ? <Mic2 size={16} /> : <LockKeyhole size={15} />}</span><span className="flex-1 text-sm">{x}</span><ChevronRight size={15} className="text-white/25" /></button>)}</div><button onClick={() => setUnlocked(false)} className="mt-8 flex items-center gap-2 text-xs text-white/35" data-testid="button-lock-secret"><LockKeyhole size={14} /> lock again</button></div>; }

function NoteDetail({ store, detail, setDetail }: { store: PhoneStore; detail: Detail; setDetail: (d: Detail) => void }) { const n = store.notes.find(x => x.id === detail?.id) ?? store.notes[0]; return <div><button onClick={() => setDetail(null)} className="mb-5 flex items-center gap-2 text-sm text-[#e5a9b3]" data-testid="button-note-back"><ArrowLeft size={15} /> notes</button><p className="text-xs text-white/45">edited today · on this phone</p><h1 className="mt-3 font-serif text-4xl leading-tight">{n.title}</h1><div className="mt-8 whitespace-pre-line text-[15px] leading-8 text-white/70">{n.body}</div><button className="mt-10 flex items-center gap-2 text-xs text-white/40" data-testid="button-edit-note"><Pencil size={14} /> edit this note</button></div>; }

function EditPanel({ onClose, store, setStore }: { onClose: () => void; store: PhoneStore; setStore: React.Dispatch<React.SetStateAction<PhoneStore>> }) {
  const [kind, setKind] = useState('quick'); const [text, setText] = useState('');
  const [role, setRole] = useState(''); const [context, setContext] = useState('');
  const submit = () => {
    if (!text.trim()) return;
    if (kind === 'contact') {
      setStore(s => createContact(s, { name: text, role, context }));
    } else {
      const id = `local-${Date.now()}`;
      setStore(s => { if (kind === 'quick') return { ...s, quickNotes: [{ id, text, time: 'just now', color: '#d895a6' }, ...s.quickNotes] }; if (kind === 'diary') return { ...s, diary: [{ id, date: 'Today', title: text.slice(0, 28), mood: 'unfolding', body: text }, ...s.diary] }; if (kind === 'event') return { ...s, events: [...s.events, { id, day: 28, title: text, time: '19:00', kind: 'personal' }] }; return s; });
    }
    setText(''); onClose();
  };
  return <div className="fixed inset-0 z-30 flex items-end bg-black/45 backdrop-blur-sm"><div className="mx-auto w-full max-w-[402px] rounded-t-[30px] border-t border-white/15 bg-[#1b1828] p-5 shadow-2xl app-in"><div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#dca4b1]">edit mode</p><h2 className="mt-1 font-serif text-2xl">Add something</h2></div><button onClick={onClose} className="rounded-full p-2 text-white/50 hover:bg-white/10" data-testid="button-close-edit-panel"><X size={18} /></button></div><div className="mb-4 flex gap-2 overflow-x-auto">{[['quick','quick note'],['diary','diary page'],['event','calendar event'],['contact','contact']].map(([v,l]) => <button key={v} onClick={() => setKind(v)} className={`shrink-0 rounded-full border px-3 py-2 text-[11px] ${kind === v ? 'border-[#d98ca7] bg-[#d98ca7]/15 text-[#efbac4]' : 'border-white/10 text-white/45'}`} data-testid={`button-edit-kind-${v}`}>{l}</button>)}</div><textarea value={text} onChange={e => setText(e.target.value)} placeholder={kind === 'contact' ? 'contact name' : kind === 'quick' ? 'a thought before it disappears…' : kind === 'diary' ? 'what happened today?' : 'what is happening?'} className="h-28 w-full resize-none rounded-2xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-white outline-none placeholder:text-white/25 focus:border-[#d98ca7]" data-testid="textarea-edit-content" />{kind === 'contact' && <div className="mt-2 space-y-2"><input value={role} onChange={e => setRole(e.target.value)} placeholder="Role" className="w-full rounded-xl border border-white/10 bg-white/5 p-3 text-sm outline-none" /><input value={context} onChange={e => setContext(e.target.value)} placeholder="Context" className="w-full rounded-xl border border-white/10 bg-white/5 p-3 text-sm outline-none" /></div>}<button onClick={submit} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#d98ca7] py-3 text-sm text-[#291d26]" data-testid="button-save-edit"><Plus size={16} /> save to phone</button><p className="mt-3 text-center text-[10px] text-white/30">local edits survive refresh</p></div></div>;
}

function SettingsPanel({ onClose, editMode, setEditMode, onOpenAdmin }: { onClose: () => void; editMode: boolean; setEditMode: (v: boolean) => void; onOpenAdmin: () => void }) { return <div className="fixed inset-0 z-30 flex items-end bg-black/45 backdrop-blur-sm"><div className="mx-auto w-full max-w-[402px] rounded-t-[30px] border-t border-white/15 bg-[#1b1828] p-5 app-in"><div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#dca4b1]">phone settings</p><h2 className="mt-1 font-serif text-2xl">A little control room</h2></div><button onClick={onClose} className="rounded-full p-2 text-white/50 hover:bg-white/10" data-testid="button-close-settings"><X size={18} /></button></div><div className="space-y-2"><button onClick={() => setEditMode(!editMode)} className="flex w-full items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4 text-left" data-testid="button-settings-edit-mode"><Pencil size={17} className="text-[#e2a7b4]" /><span className="flex-1"><b className="block text-sm">Edit Mode</b><small className="text-[10px] text-white/40">add, remove, and shape the little details</small></span><span className={`h-5 w-9 rounded-full p-0.5 ${editMode ? 'bg-[#d98ca7]' : 'bg-white/15'}`}><span className={`block h-4 w-4 rounded-full bg-white transition-transform ${editMode ? 'translate-x-4' : ''}`} /></span></button><button onClick={onOpenAdmin} className="flex w-full items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4 text-left"><Settings size={17} className="text-[#e2a7b4]" /><span className="flex-1"><b className="block text-sm">Story Admin</b><small className="text-[10px] text-white/40">generate activity and edit canon</small></span></button><div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4"><ShieldCheck size={17} className="text-[#b9d0b4]" /><span><b className="block text-sm">Private by design</b><small className="text-[10px] text-white/40">fictional roleplay material · stored locally</small></span></div></div></div></div>; }

function Phone() {
  const [store, setStore, publish] = usePhoneStore(); const [openApp, setOpenApp] = useState<AppId | null>(null); const [detail, setDetail] = useState<Detail>(null); const [settings, setSettings] = useState(false); const [editMode, setEditMode] = useState(false); const [editPanel, setEditPanel] = useState(false); const [unlocked, setUnlocked] = useState(false); const [admin, setAdmin] = useState(false);
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') { if (admin) setAdmin(false); else if (detail) setDetail(null); else if (openApp) setOpenApp(null); else setSettings(false); } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [detail, openApp, admin]);
  const goHome = () => { setOpenApp(null); setDetail(null); };
  const page = useMemo(() => { if (!openApp) return null; const common = { id: openApp, onBack: goHome, onSettings: () => setSettings(true), editMode, onEdit: () => setEditPanel(true) }; let body: ReactNode; switch (openApp) { case 'phone': body = <PhoneApp store={store} setStore={setStore} detail={detail} setDetail={setDetail} editMode={editMode} />; break; case 'messages': body = <Messages store={store} setStore={setStore} detail={detail} setDetail={setDetail} editMode={editMode} />; break; case 'instagram': body = <Instagram store={store} detail={detail} setDetail={setDetail} />; break; case 'echo': body = <EchoApp store={store} setStore={setStore} editMode={editMode} />; break; case 'gallery': body = <Gallery store={store} setStore={setStore} detail={detail} setDetail={setDetail} editMode={editMode} />; break; case 'music': body = <Music detail={detail} setDetail={setDetail} />; break; case 'studio': body = <StudioApp store={store} setStore={setStore} editMode={editMode} />; break; case 'diary': body = <Diary store={store} setStore={setStore} detail={detail} setDetail={setDetail} editMode={editMode} />; break; case 'notes': body = detail?.kind === 'note' ? <NoteDetail store={store} detail={detail} setDetail={setDetail} /> : <Notes store={store} setDetail={setDetail} />; break; case 'quick': body = <QuickNotes store={store} setStore={setStore} editMode={editMode} />; break; case 'voice': body = <Voice store={store} setDetail={setDetail} detail={detail} setStore={setStore} editMode={editMode} />; break; case 'calendar': body = <Calendar store={store} setStore={setStore} editMode={editMode} />; break; case 'places': body = <PlacesApp store={store} setStore={setStore} editMode={editMode} />; break; case 'browser': body = <BrowserApp store={store} setStore={setStore} editMode={editMode} />; break; case 'contacts': body = <Contacts store={store} detail={detail} setDetail={setDetail} />; break; case 'notifications': body = <Notifications store={store} />; break; case 'files': body = <Files store={store} />; break; case 'screentime': body = <ScreenTimeApp store={store} />; break; case 'secret': body = <Secret unlocked={unlocked} setUnlocked={setUnlocked} />; break; default: body = null; } return <Shell {...common}><ApprovedExtras store={store} app={openApp} detail={detail} setDetail={setDetail} />{body}</Shell>; }, [openApp, detail, store, editMode, unlocked]);
  return <div className="noise min-h-[100dvh] py-0 sm:flex sm:items-center sm:justify-center sm:py-5">{page ?? <Home onOpen={(id) => { setDetail(null); setOpenApp(id); }} onSettings={() => setSettings(true)} />}{settings && <SettingsPanel onClose={() => setSettings(false)} editMode={editMode} setEditMode={setEditMode} onOpenAdmin={() => { setSettings(false); setAdmin(true); }} />}{editPanel && openApp && <EditPanel onClose={() => setEditPanel(false)} store={store} setStore={setStore} />}{admin && <StoryAdmin store={store} setStore={setStore} onPublish={publish} onClose={() => setAdmin(false)} />}</div>;
}

function Router() { const [location] = useLocation(); return <ErrorBoundary resetKey={location}><Switch><Route path="/" component={Phone} /><Route component={() => <Phone />} /></Switch></ErrorBoundary>; }
function App() { return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><Router /></WouterRouter><Toaster /></TooltipProvider></QueryClientProvider>; }
export default App;